server:
  port: 8088
  servlet:
    context-path: /

spring:
  application:
    name: bakis-back-end
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  main:
    banner-mode: "off"
  mvc:
    format:
      date: iso
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    driver-class-name: com.mysql.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

httpclient:
  timeout: 10000

springdoc:
  swagger-ui:
    enabled: true

security:
  jwt:
    secret-key: LlN8P3NHGJzWiGjHVaMzfDQqObR4JBrqkbtF7PgxRsk=